# Generated by Django 4.0 on 2021-12-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['author'],
            },
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
